VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ViSession"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

''' <summary> Initializes an IEEE488 Session. </summary>
Private Sub Class_Initialize()
End Sub

''' <summary> Termiantes an IEEE488 Session. </summary>
Private Sub Class_Terminate()
End Sub
